version: '3'
services:
  symfony:
    build:
      context: .
      args:
        - PHP_EXTENSIONS=mysqli
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony123!
      MYSQL_ROOT_PASSWORD: symfony123!
    ports:
      - "3306:3306"
  symfonysetup:
    build:
      context: .
    restart: "no"
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
      - symfony
    entrypoint: ["bash", "-c", "sleep 15 && php bin/console doctrine:migrations:migrate --no-interaction && php bin/console doctrine:database:create && php bin/console doctrine:migrations:migrate"]
