version: '3'
services:
  symfony:
    build:
      context: .
      args:
        - PHP_EXTENSIONS=mysqli
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony123!
      MYSQL_ROOT_PASSWORD: symfony123!
    ports:
      - "3306:3306"
    
