CREATE DATABASE IF NOT EXISTS symfony;
USE symfony;

CREATE TABLE IF NOT EXISTS Entry(
	id INT AUTO_INCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	tlf INT,
	cat ENUM("Hotel", "Pista", "Complemento") NOT NULL,
	is_active BOOLEAN NOT NULL,
	created_at TIMESTAMP NOT NULL,
	last_modified TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);