index:
    path: /
    controller: App\Controller\DefaultController::index
edit:
    path: /edit
    controller: App\Controller\EditorController::editEntry
new:
    path: /new
    controller: App\Controller\NewEntryController::createNewForm

    